AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.
Resources:
  gateway:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          AWS_TABLE_NAME: 'MyItemTable'
          AWS_REGION: 'ap-southeast-2'
          AWS_ENDPOINT: 'http://dynamodb.ap-southeast-2.amazonaws.com'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /gateway
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path: /gateway/{itemId}
            Method: ANY
